#! /bin/sh
# /etc/init.d/weatherstation

### BEGIN INIT INFO
# Provides:          weatherstation
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       TODO
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting weatherstation"
    # run application you want to start
    nohup /usr/local/bin/weather_station.py &> /tmp/weatherstation.log
    ;;
  stop)
    echo "Stopping weatherstation"
    # kill application you want to stop
    pkill -f /usr/local/bin/weather_station.py 
    ;;
  *)
    echo "Usage: /etc/init.d/weatherstation {start|stop}"
    exit 1
    ;;
esac

exit 0
